# Generated by Django 4.0.4 on 2022-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.JSONField()),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=900)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('zip_code', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.CharField(max_length=900)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='media/images')),
            ],
        ),
    ]
