# Generated by Django 4.0.4 on 2022-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EMail', models.EmailField(max_length=15)),
                ('TellMe', models.CharField(max_length=2000)),
            ],
        ),
    ]
