# Generated by Django 4.0.4 on 2023-01-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contactus_email_alter_contactus_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='LastName',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='EMail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='TellMe',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
