# Generated by Django 4.0.4 on 2023-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_contactus_firstname_remove_contactus_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='TellMe',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
